name       : Sphinx ghpages
on         :
  push:
    branches:
      - main

env        :
  PY_VER       : '3.11'
  AWS_REGION   : ap-southeast-1
  INSTANCE_NAME: thy1
  PORT_INFO    : fromPort=22,protocol=TCP,toPort=22

permissions:
  contents: read
  pages   : write
  id-token: write

concurrency:
  group             : "ghpages"
  cancel-in-progress: true

jobs       :

  make_html:
    if     : endsWith(github.repository, '.github.io')
    environment:
      name: github-pages
      url : ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps  :
      - name: Checkout
        uses: actions/checkout@v3

      # Python
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VER }}
          cache         : 'pip'

      - name: pip install
        run: pip install -r requirements.txt

      # Sphinx
      - name: sphinx make html
        run: make html

#      - name: Setup Pages
#        uses: actions/configure-pages@v2
#
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
